spring.config.encoding=UTF-8
# Disable Hibernate auto schema generation
spring.jpa.hibernate.ddl-auto=none

# Enable schema.sql and data.sql execution
spring.sql.init.mode=always

# Execution order: scripts first, then JPA
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:h2:file:./db/filmorate;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin