spring.config.encoding=UTF-8
# ========== ?????? ??????????? ==========
# ???????? ??????? (??? ???? ????????)
logging.level.root=INFO
# ??????? ??? ?????? ?????????? (??? ?????? ? ??????)
logging.level.ru.yandex.practicum.filmorate=DEBUG
# ??? ???????? ?????
logging.file.name=logs/application.log
# ??????? ??? ???????? ?????? ? ?????
logging.logback.rollingpolicy.file-name-pattern=logs/application-%d{yyyy-MM-dd}.%i.log.gz
# ???????????? ?????? ?????
logging.logback.rollingpolicy.max-file-size=10MB
# ??????? ???? ?? 30 ????
logging.logback.rollingpolicy.max-history=30
# ?????? ?????????
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
